### PR TITLE
update year

### PR DESCRIPTION
**Pull request by oalders**
- Update links to use more recent examples
- Swap out mailto link for github issues

### CODE REVIEW

**Review by simbabque — COMMENTED** [review]
I like the newer examples, I think we should have those. But there are also changes for the issues vs mail in index.md. If you see #5 I already proposed those and the one in accepted.md. Let's check which one we want.

**Comment by oalders** [comment]
Yes, we have a collision here. :) Probably a good argument for having made two PRs out of the two commits. I did comment on your PR with my reasoning. Let me know what you think.

**Comment by oalders** [comment]
I wasn't paying attention. The file's name was `accepted.md`, so of course the GH issue would already exist. I've removed that commit now.

**Review by simbabque — COMMENTED** [review]
Thank you for clearing that up! :)

**Review by simbabque — APPROVED** [review]

**Pull request merged**
